// <auto-generated />
using System;
using BlackHole.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackHole.DataAccess.Migrations
{
    [DbContext(typeof(BlackHoleContext))]
    partial class BlackHoleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlackHole.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachamentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AttachmentTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Obejct")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("AttachmentTypeId");

                    b.ToTable("tblAttachment");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.AttachmentType", b =>
                {
                    b.Property<int>("AttachmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentTypeId"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttachmentTypeId");

                    b.ToTable("tblAttachmentType");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId");

                    b.HasIndex("LastMessageId")
                        .IsUnique()
                        .HasFilter("[LastMessageId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("tblConversation");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastConversationConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("LastConversationConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("tblMessage");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.UserConversation", b =>
                {
                    b.Property<Guid>("UserConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserConversationId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserConversation");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("BlackHole.Domain.Entities.AttachmentType", "AttachmentType")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentTypeId");

                    b.Navigation("AttachmentType");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("BlackHole.Domain.Entities.Message", "LastMessage")
                        .WithOne("Conversation")
                        .HasForeignKey("BlackHole.Domain.Entities.Conversation", "LastMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BlackHole.Domain.Entities.User", null)
                        .WithMany("Conversations")
                        .HasForeignKey("UserId");

                    b.Navigation("LastMessage");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Message", b =>
                {
                    b.HasOne("BlackHole.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("BlackHole.Domain.Entities.Conversation", "LastConversation")
                        .WithMany()
                        .HasForeignKey("LastConversationConversationId");

                    b.HasOne("BlackHole.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("LastConversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.UserConversation", b =>
                {
                    b.HasOne("BlackHole.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackHole.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.AttachmentType", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.Message", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BlackHole.Domain.Entities.User", b =>
                {
                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
