name: API Build, Test, Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feat/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: BlackHoleAPI
  
    - name: Build
      run: dotnet build --no-restore
      working-directory: BlackHoleAPI
  
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: BlackHoleAPI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Test
      working-directory: BlackHoleAPI/BlackHole.UnitTests
      run: dotnet test --no-build --verbosity normal
